### ISSUE TITLE
Furnus crashing under 0.2.9

### ISSUE THREAD

**Issue by meradudd** [F4ndroid/FrenchToast#4]
Updated to 0.2.9 today and find that any time I open the GUI for the furnus or pulvus, I get a crash as soon as the GUI shows.  This was not happening before the update.

Playing on SSP, crash log attached

[2016-12-17-6.log.gz](https://github.com/F4ndroid/FrenchToast/files/659207/2016-12-17-6.log.gz)

**Comment by F4ndroid** [comment]
Fixed in 0.2.9.1
